#!/bin/bash
DOTFILES_PATH=$(pwd)
CONFIG_PATH=$HOME/.config
LOCAL_PATH=$HOME/.local

# link nvim config
ln -s $DOTFILES_PATH/config/nvim $HOME/.config
# link dmenu to config (not necessary but I like it there)
ln -s $DOTFILES_PATH/config/dmenu $HOME/.config
