#!/bin/bash

source paths

# link nvim config
ln -s $DOTFILES_PATH/config/nvim $CONFIG_PATH
# link dmenu and dwm to config (not necessary but I like it there)
ln -s $DOTFILES_PATH/config/dmenu $CONFIG_PATH
ln -s $DOTFILES_PATH/config/dwm $CONFIG_PATH
ln -s $DOTFILES_PATH/config/st $CONFIG_PATH

# link local/bin
for file in "$DOTFILES_PATH/local/bin"/*; do
    ln -s "$file" "$LOCAL_BIN_PATH"
done

# link home/ and make the files hidden
for file in "$DOTFILES_PATH/home"/*; do
	ln -s $file "$HOME/.$(basename "$file")"
done
